### ISSUE TITLE
Inheritance of options? *QUESTION*

### ISSUE THREAD

**Issue by AliOsseili** [MaraniMatias/grunt-electron-packager#3]
Hello, I was wondering if there was a way in grunt to sort of make a "template" of the options so different builds can be shorter. Right now I have something like this

'electron-packager': {
    buildWithIMZ: {
        options: {
            platform        : os.platform(),
            arch            : os.arch(),
            dir             : '.',
            out             : '../gameBuilds/buildWithIMZ',
            name            : artifactIdIMZ,
            executableName  : 'run',
            electronVersion : '1.8.2',
            asar            : true,
            overwrite       : true
        }
    },
    buildWithoutIMZ: {
        options: {
            platform        : os.platform(),
            arch            : os.arch(),
            dir             : '.',
            out             : '../gameBuilds/buildWithoutIMZ',
            name            : artifactIdNonIMZ,
            executableName  : 'run',
            electronVersion : '1.8.2',
            asar            : true,                  
            overwrite       : true
        }

but I'd like for it to be like this:

default: {
 options: {
   platform : os.platform(),
   arch : os.arch(),
   dir : '.',
   executableName : 'run',
   electronVersion : '1.8.2',
   asar : true,
  overwrite : true
 }
},
buildWithIMZ: {
  options: {
  out : '../gameBuilds/buildWithIMZ',
  name : artifactId . '-imz'
  }
  },
  buildWithoutIMZ: {
   options: {
   out : '../gameBuilds/buildWithoutIMZ',
   name : artifactId . '-noimz'
  }
}

So that all the tasks do is just look at the rest of the options in the one named default then use what they have inside them. Is this possible or a feature to be? if its not included yet, how can I make make it so its possible to "inherit" options?

**Comment by AliOsseili** [comment]
@MaraniMatias

**Comment by MaraniMatias** [comment]
Hello, I apologize for the delay in my response.

I'm currently busy

I think it could be done,
Do you know if there is a way to do it with Grunt?

I'm going to try to implement your idea, also if you want to do a pull-request.

Thanks for your contribution

**Comment by MaraniMatias** [comment]
In the next version you can use the settings as you requested, [See Readme](https://github.com/MaraniMatias/grunt-electron-packager#global-options).

Also in the version you use, by means of the option function you can do what you asked.


If you give me a star for my work, I will appreciate. It helps a lot and it's free: D

**Comment by AliOsseili** [comment]
Thank you so much for adding this feature @MaraniMatias . Helps make my code look less copy pasty like lol. Sorry for the late response but I was away for the weekend but am glad to be back 😄
